version: '3.0'
networks:
  docker-teknasyon-network:
services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: "docker-teknasyon-php"
    volumes:
      - "..:/var/www/html"
    ports:
      - "9999:9000"
    networks:
      - docker-teknasyon-network
  mysql:
    image: mysql:5.7.22
    container_name: "docker-teknasyon-mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "teknasyon"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "docker"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - docker-teknasyon-network
  web:
    image: nginx:stable-alpine
    container_name: "docker-teknasyon-nginx"
    ports:
      - "8000:80"
    volumes:
      - "..:/var/www/html"
      - "../storage/app/public:/var/www/html/public/storage"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql
    networks:
      - docker-teknasyon-network
